version: '3.8'

services:
  frontend:
    build:
      context: ./proyectogent-main
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    build:
      context: ./DB
    container_name: postgres-db
    env_file:
      - ./DB/.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
